services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=quelocura

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quelocura
    ports:
      - "3306:3306"
    volumes:
      - ./Sql/quelocura.sql:/docker-entrypoint-initdb.d/quelocura.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: